name: CI

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/setup@v3
        with:
          version: 12
          runtime: node@22
          install: false
          cache: true

      - name: Ensure node and pnpm are installed
        run: |
          node -v
          pnpm -v
      
      - name: Install deps
        run: pnpm i --frozen-lockfile
